[package]
name = "eudidcomm"
version = "0.1.0"
edition = "2021"

[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

members = ["alice_http", "bob_http", "did", "protocol"]
